### ISSUE TITLE
Questions about multi-metrics optimization

### ISSUE THREAD

**Issue by Penguin135** [addb-swstarlab/DARK#1]
Hello!

I am also a developer of DBMS, especially in RocksDB.
As far as I know, there is more than one metric that can be optimized (ex. latency, throughput), how can I apply RS-OtterTune to this multi-optimization subject, specifically?

**Comment by addb-swstarlab** [comment]
It is difficult to optimize both throughput and latency at the same time. We are going to do some related research about this subject sooner or later.
