### ISSUE TITLE
Questions about the design of the DNN model

### ISSUE THREAD

**Issue by Juneum** [addb-swstarlab/DARK#3]
How did you design your DNN model since there is not just one output metric?

**Comment by kimkyeonghun** [comment]
We design two types of DNN.
The first is the "twice" model. It shares weights in the previous dense layers. When they reach the last prediction, they predict the output metric to use different N(N=2) dense layers.
The second is the "double" model. It only shares input. The input is putting at different two DNN models. They expect output metrics independently. It is the same as two single DNN models.
